"""
Multi-Biome Environment & Road Presets (CP-03).
Covers:
  - Desert Branching Dunes & Caravan Roads
  - Green Mossy Mountains, Rocks & Grassy Alpine Passes
  - Lush Valleys with Moss, Stones & Winding Game Trails
  - Savanna Explanadas / Plateaus / Mesas (Kopjes)
  - Fantasy Game Landscapes (Terraced Plateaus, Mystical Moss & Carved Stone Paths)
"""

from typing import Dict, Any
from ..config import (
    TerrainEngineParams,
    EnvironmentBiome,
    DuneMorphology,
    RoadStyle,
)


DESERT_PRESETS: Dict[str, Dict[str, Any]] = {
    "cinematic_branching_erg": {
        "label": "🏜️ Deserto Cinematográfico em Teia + Estrada",
        "description": "Dunas sinuosas com ramificações em Y (efeito árvore/rio/teia) cortadas por uma estrada alisada.",
        "params": {
            "environment_type": EnvironmentBiome.DESERT,
            "dune_morphology": DuneMorphology.BRANCHING_ERG,
            "existing_relief_keep": 0.0,
            "dune_scale": 12.0,
            "dune_density": 1.25,
            "dune_height": 26.0,
            "dune_variation": 2.4,
            "wind_turbulence": 1.6,
            "wind_direction_deg": 32.0,
            "dune_branching": 0.80,
            "branch_anisotropy": 3.2,
            "crest_roundness": 0.44,
            "dune_sharpness": 1.35,
            "plateau_flattening": 0.0,
            "terrace_steps": 0.0,
            "macro_basin_height": 14.0,
            "macro_basin_scale": 16.0,
            "medium_undulation_height": 3.2,
            "mesh_smooth_iterations": 8,
            "mesh_smooth_factor": 0.72,
            "enable_road": True,
            "road_style": RoadStyle.DESERT_TRACK,
            "road_width_m": 14.0,
            "road_shoulder_m": 24.0,
            "road_flatten_strength": 0.90,
            "road_elevation_follow": 0.65,
            "road_carve_depth_m": -0.4,
            "road_berm_height_m": 0.9,
            "road_meander_amplitude": 95.0,
            "road_meander_scale": 12.0,
            "road_secondary_branch": True,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 2.8,
            "pbr_blend_factor": 0.72,
            "rock_slope_threshold": 0.62,
            "moss_moisture_amount": 0.15,
            "color_sand_primary": (0.72, 0.34, 0.18, 1.0),
            "color_sand_crest": (0.86, 0.48, 0.26, 1.0),
            "color_sand_trough": (0.46, 0.19, 0.10, 1.0),
            "color_rock": (0.28, 0.16, 0.11, 1.0),
            "color_moss": (0.38, 0.32, 0.16, 1.0),
            "color_road": (0.42, 0.26, 0.16, 1.0),
        },
    },
    "green_mossy_mountains": {
        "label": "🏔️ Montanhas Verdes (Musgo, Pedras, Relva & Estrada)",
        "description": "Cordilheiras montanhosas com penhascos de rocha nas encostas íngremes, relva verde, musgo húmido e estrada de montanha.",
        "params": {
            "environment_type": EnvironmentBiome.MOUNTAIN_ALPINE,
            "dune_morphology": DuneMorphology.ALPINE_MOUNTAINS,
            "existing_relief_keep": 0.0,
            "dune_scale": 16.0,
            "dune_density": 1.35,
            "dune_height": 58.0,
            "dune_variation": 3.2,
            "wind_turbulence": 2.6,
            "wind_direction_deg": 25.0,
            "dune_branching": 1.45,
            "branch_anisotropy": 1.8,
            "crest_roundness": 0.28,
            "dune_sharpness": 1.55,
            "plateau_flattening": 0.0,
            "terrace_steps": 0.0,
            "macro_basin_height": 28.0,
            "macro_basin_scale": 18.0,
            "medium_undulation_height": 6.5,
            "mesh_smooth_iterations": 6,
            "mesh_smooth_factor": 0.65,
            "enable_road": True,
            "road_style": RoadStyle.STONE_PAVED,
            "road_width_m": 13.0,
            "road_shoulder_m": 22.0,
            "road_flatten_strength": 0.92,
            "road_elevation_follow": 0.55,
            "road_carve_depth_m": -0.6,
            "road_berm_height_m": 0.6,
            "road_meander_amplitude": 115.0,
            "road_meander_scale": 11.0,
            "road_secondary_branch": True,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 3.2,
            "pbr_blend_factor": 0.22,  # Usa o detalhe micro da PBR mas domina a paleta Verde/Musgo/Rocha!
            "rock_slope_threshold": 0.84,
            "moss_moisture_amount": 0.68,
            "color_sand_primary": (0.14, 0.34, 0.08, 1.0),  # Relva verde de montanha
            "color_sand_crest": (0.24, 0.44, 0.12, 1.0),    # Relva iluminada pelo sol
            "color_sand_trough": (0.06, 0.20, 0.04, 1.0),   # Musgo profundo dos vales
            "color_rock": (0.20, 0.21, 0.22, 1.0),          # Rocha granítica / ardósia
            "color_moss": (0.09, 0.28, 0.06, 1.0),          # Musgo húmido
            "color_road": (0.32, 0.29, 0.26, 1.0),          # Caminho de pedra/terra batida
        },
    },
    "lush_moss_valley": {
        "label": "🌿 Vale Verdejante (Relva, Musgo, Pedras & Caminho)",
        "description": "Colinas suaves de relva e musgo com afloramentos rochosos e um caminho sinuoso com bifurcação.",
        "params": {
            "environment_type": EnvironmentBiome.LUSH_VALLEY,
            "dune_morphology": DuneMorphology.BRANCHING_ERG,
            "existing_relief_keep": 0.0,
            "dune_scale": 18.0,
            "dune_density": 1.0,
            "dune_height": 22.0,
            "dune_variation": 2.8,
            "wind_turbulence": 1.8,
            "wind_direction_deg": 15.0,
            "dune_branching": 0.90,
            "branch_anisotropy": 2.4,
            "crest_roundness": 0.58,
            "dune_sharpness": 1.15,
            "plateau_flattening": 0.25,
            "terrace_steps": 0.0,
            "macro_basin_height": 16.0,
            "macro_basin_scale": 20.0,
            "medium_undulation_height": 3.5,
            "mesh_smooth_iterations": 10,
            "mesh_smooth_factor": 0.78,
            "enable_road": True,
            "road_style": RoadStyle.MOSSY_PATH,
            "road_width_m": 12.0,
            "road_shoulder_m": 20.0,
            "road_flatten_strength": 0.90,
            "road_elevation_follow": 0.75,
            "road_carve_depth_m": -0.35,
            "road_berm_height_m": 0.4,
            "road_meander_amplitude": 105.0,
            "road_meander_scale": 10.0,
            "road_secondary_branch": True,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 3.0,
            "pbr_blend_factor": 0.18,
            "rock_slope_threshold": 0.88,
            "moss_moisture_amount": 0.75,
            "color_sand_primary": (0.16, 0.40, 0.09, 1.0),
            "color_sand_crest": (0.28, 0.52, 0.14, 1.0),
            "color_sand_trough": (0.07, 0.24, 0.05, 1.0),
            "color_rock": (0.25, 0.24, 0.22, 1.0),
            "color_moss": (0.10, 0.33, 0.07, 1.0),
            "color_road": (0.36, 0.28, 0.20, 1.0),
        },
    },
    "savanna_plains_kopjes": {
        "label": "🦁 Savana & Explanadas (Terra Vermelha, Relva & Planaltos)",
        "description": "Grandes explanadas abertas intercaladas com planaltos/mesas rochosas, relva dourada seca e estrada de terra vermelha.",
        "params": {
            "environment_type": EnvironmentBiome.SAVANNA_PLAINS,
            "dune_morphology": DuneMorphology.SAVANNA_EXPLANADA,
            "existing_relief_keep": 0.0,
            "dune_scale": 22.0,
            "dune_density": 0.95,
            "dune_height": 28.0,
            "dune_variation": 2.2,
            "wind_turbulence": 1.4,
            "wind_direction_deg": 20.0,
            "dune_branching": 0.75,
            "branch_anisotropy": 2.0,
            "crest_roundness": 0.38,
            "dune_sharpness": 1.60,
            "plateau_flattening": 0.65,
            "terrace_steps": 0.0,
            "macro_basin_height": 10.0,
            "macro_basin_scale": 25.0,
            "medium_undulation_height": 2.2,
            "mesh_smooth_iterations": 9,
            "mesh_smooth_factor": 0.74,
            "enable_road": True,
            "road_style": RoadStyle.DIRT_TRAIL,
            "road_width_m": 15.0,
            "road_shoulder_m": 26.0,
            "road_flatten_strength": 0.92,
            "road_elevation_follow": 0.80,
            "road_carve_depth_m": -0.3,
            "road_berm_height_m": 0.5,
            "road_meander_amplitude": 90.0,
            "road_meander_scale": 14.0,
            "road_secondary_branch": True,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 2.8,
            "pbr_blend_factor": 0.38,
            "rock_slope_threshold": 0.82,
            "moss_moisture_amount": 0.45,
            "color_sand_primary": (0.58, 0.44, 0.16, 1.0),  # Relva dourada da savana
            "color_sand_crest": (0.72, 0.56, 0.22, 1.0),    # Capim seco ao sol
            "color_sand_trough": (0.48, 0.20, 0.09, 1.0),   # Terra vermelha africana (laterite)
            "color_rock": (0.30, 0.22, 0.17, 1.0),          # Rocha de kopje / planalto
            "color_moss": (0.22, 0.34, 0.10, 1.0),          # Vegetação verde junto às baixas
            "color_road": (0.52, 0.22, 0.10, 1.0),          # Estrada de terra vermelha batida
        },
    },
    "fantasy_terraced_peaks": {
        "label": "✨ Paisagem Fantasiosa para Jogos (Terraços, Musgo & Estrada)",
        "description": "Cenário estilizado para jogos: terraços orgânicos esculpidos, pilares rochosos, musgo esmeralda e estrada real.",
        "params": {
            "environment_type": EnvironmentBiome.FANTASY_LANDSCAPE,
            "dune_morphology": DuneMorphology.FANTASY_TERRACES,
            "existing_relief_keep": 0.0,
            "dune_scale": 15.0,
            "dune_density": 1.3,
            "dune_height": 48.0,
            "dune_variation": 3.5,
            "wind_turbulence": 2.2,
            "wind_direction_deg": 38.0,
            "dune_branching": 1.25,
            "branch_anisotropy": 1.6,
            "crest_roundness": 0.35,
            "dune_sharpness": 1.45,
            "plateau_flattening": 0.45,
            "terrace_steps": 6.0,
            "macro_basin_height": 22.0,
            "macro_basin_scale": 16.0,
            "medium_undulation_height": 5.0,
            "mesh_smooth_iterations": 8,
            "mesh_smooth_factor": 0.70,
            "enable_road": True,
            "road_style": RoadStyle.STONE_PAVED,
            "road_width_m": 16.0,
            "road_shoulder_m": 25.0,
            "road_flatten_strength": 0.94,
            "road_elevation_follow": 0.50,
            "road_carve_depth_m": -0.5,
            "road_berm_height_m": 0.7,
            "road_meander_amplitude": 110.0,
            "road_meander_scale": 11.0,
            "road_secondary_branch": True,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 3.0,
            "pbr_blend_factor": 0.20,
            "rock_slope_threshold": 0.85,
            "moss_moisture_amount": 0.72,
            "color_sand_primary": (0.10, 0.42, 0.22, 1.0),  # Relva esmeralda fantasiosa
            "color_sand_crest": (0.22, 0.60, 0.30, 1.0),    # Topo luminoso de musgo
            "color_sand_trough": (0.05, 0.22, 0.16, 1.0),   # Vales místicos profundos
            "color_rock": (0.16, 0.18, 0.24, 1.0),          # Rocha basáltica azulada
            "color_moss": (0.12, 0.48, 0.28, 1.0),          # Musgo vivo
            "color_road": (0.40, 0.37, 0.33, 1.0),          # Calçada real de pedra clara
        },
    },
    "dendritic_river_dunes": {
        "label": "🌳 Rede de Dunas Ramificadas (Árvore / Estrela / Rio)",
        "description": "Foco intenso em dunas que bifurcam e criam braços secundários como raízes ou rios de areia.",
        "params": {
            "environment_type": EnvironmentBiome.DESERT,
            "dune_morphology": DuneMorphology.DENDRITIC_WEB,
            "existing_relief_keep": 0.0,
            "dune_scale": 14.5,
            "dune_density": 1.4,
            "dune_height": 32.0,
            "dune_variation": 3.2,
            "wind_turbulence": 2.4,
            "wind_direction_deg": 24.0,
            "dune_branching": 1.35,
            "branch_anisotropy": 2.2,
            "crest_roundness": 0.40,
            "dune_sharpness": 1.40,
            "plateau_flattening": 0.0,
            "terrace_steps": 0.0,
            "macro_basin_height": 18.0,
            "macro_basin_scale": 18.0,
            "medium_undulation_height": 4.5,
            "mesh_smooth_iterations": 10,
            "mesh_smooth_factor": 0.75,
            "enable_road": False,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 2.8,
            "pbr_blend_factor": 0.72,
        },
    },
    "flowing_sahara_waves": {
        "label": "🌊 Ondas Sinuosas do Saara (Suaves & Contínuas)",
        "description": "Cordões longos e sinuosos moldados pelo vento, sem paredes retas nem degraus.",
        "params": {
            "environment_type": EnvironmentBiome.DESERT,
            "dune_morphology": DuneMorphology.SINUOUS_WAVES,
            "existing_relief_keep": 0.0,
            "dune_scale": 16.0,
            "dune_density": 1.1,
            "dune_height": 22.0,
            "dune_variation": 2.8,
            "wind_turbulence": 1.2,
            "wind_direction_deg": 40.0,
            "dune_branching": 0.42,
            "branch_anisotropy": 4.5,
            "crest_roundness": 0.52,
            "dune_sharpness": 1.25,
            "plateau_flattening": 0.0,
            "terrace_steps": 0.0,
            "macro_basin_height": 12.0,
            "macro_basin_scale": 20.0,
            "medium_undulation_height": 2.4,
            "mesh_smooth_iterations": 10,
            "mesh_smooth_factor": 0.78,
            "enable_road": False,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 3.0,
            "pbr_blend_factor": 0.70,
        },
    },
    "namib_mega_corridors": {
        "label": "🏜️ Megadunas & Corredores do Namibe (Com Estrada)",
        "description": "Dunas colossais separadas por largos vales interdunares abertos percorridos por uma estrada.",
        "params": {
            "environment_type": EnvironmentBiome.DESERT,
            "dune_morphology": DuneMorphology.MEGA_CORRIDORS,
            "existing_relief_keep": 0.0,
            "dune_scale": 24.0,
            "dune_density": 0.85,
            "dune_height": 42.0,
            "dune_variation": 2.0,
            "wind_turbulence": 1.5,
            "wind_direction_deg": 18.0,
            "dune_branching": 0.85,
            "branch_anisotropy": 3.8,
            "crest_roundness": 0.46,
            "dune_sharpness": 1.45,
            "plateau_flattening": 0.0,
            "terrace_steps": 0.0,
            "macro_basin_height": 20.0,
            "macro_basin_scale": 25.0,
            "medium_undulation_height": 4.0,
            "mesh_smooth_iterations": 9,
            "mesh_smooth_factor": 0.74,
            "enable_road": True,
            "road_width_m": 16.0,
            "road_shoulder_m": 28.0,
            "road_flatten_strength": 0.92,
            "use_pbr_maps": True,
            "pbr_tile_size_meters": 2.8,
            "pbr_blend_factor": 0.75,
        },
    },
}


def apply_preset_to_params(params: TerrainEngineParams, preset_key: str) -> TerrainEngineParams:
    """Applies a preset's values into a TerrainEngineParams instance."""
    preset = DESERT_PRESETS.get(preset_key)
    if not preset:
        return params
    params.preset_name = preset_key
    for k, v in preset["params"].items():
        if hasattr(params, k):
            setattr(params, k, v)
    return params
